// <auto-generated />
using System;
using ComuniApi.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ComuniApi.Migrations
{
    [DbContext(typeof(ComuniContext))]
    [Migration("20251124133209_Foros")]
    partial class Foros
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ComuniApi.DAL.Entidades.ComunidadEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoComunidad")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(6)
                        .HasColumnType("varchar(6)")
                        .HasDefaultValue("-");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("MaxUsers")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CodigoComunidad")
                        .IsUnique();

                    b.ToTable("Comunidades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CodigoComunidad = "WUEBOS",
                            Correo = "",
                            Direccion = "Direccion test",
                            MaxUsers = 0,
                            Nombre = "Comunidad test"
                        });
                });

            modelBuilder.Entity("ComuniApi.DAL.Entidades.ConceptoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Conceptos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Mantenimiento"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Proyecto Extraordinario"
                        });
                });

            modelBuilder.Entity("ComuniApi.DAL.Entidades.EdoCuentaEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ConceptoId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaLimite")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConceptoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("EdoCuentas");
                });

            modelBuilder.Entity("ComuniApi.DAL.Entidades.ForoComentarioEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ForoId")
                        .HasColumnType("int");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ForoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("ForoComentarios");
                });

            modelBuilder.Entity("ComuniApi.DAL.Entidades.ForoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ComunidadId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ComunidadId");

                    b.ToTable("Foros");
                });

            modelBuilder.Entity("ComuniApi.DAL.Entidades.IncidenciaEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("EstatusId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EstatusId");

                    b.HasIndex("UserId");

                    b.ToTable("Incidencias");
                });

            modelBuilder.Entity("ComuniApi.DAL.Entidades.IncidenciaEstatusEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("IncidenciasEstatus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Pendiente"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "En Proceso"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Cerrada"
                        });
                });

            modelBuilder.Entity("ComuniApi.DAL.Entidades.ReporteEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("EstatusId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EstatusId");

                    b.HasIndex("UserId");

                    b.ToTable("Reportes");
                });

            modelBuilder.Entity("ComuniApi.DAL.Entidades.ReporteEstatusEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("ReportesEstatus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Pendiente"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "En Proceso"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Resuelto"
                        });
                });

            modelBuilder.Entity("ComuniApi.DAL.Entidades.RolEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Usuario"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Administrador"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Super Administrador"
                        });
                });

            modelBuilder.Entity("ComuniApi.DAL.Entidades.UsuarioEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ComunidadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ComunidadId");

                    b.HasIndex("RolId");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ComunidadId = 1,
                            Email = "",
                            NombreCompleto = "Administrador Principal",
                            PasswordHash = "AQAAAAIAAYagAAAAEJMWmqGEeofwL3f2r0uCFpykRHUwRHd2S3axzTA2Ox0AVE1hxv7oB/FeWzQJcPb/aA==",
                            RolId = 3,
                            Username = "administrador"
                        },
                        new
                        {
                            Id = 2,
                            ComunidadId = 1,
                            Email = "",
                            NombreCompleto = "Administrador",
                            PasswordHash = "AQAAAAIAAYagAAAAEJMWmqGEeofwL3f2r0uCFpykRHUwRHd2S3axzTA2Ox0AVE1hxv7oB/FeWzQJcPb/aA==",
                            RolId = 2,
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("ComuniApi.DAL.Entidades.EdoCuentaEntity", b =>
                {
                    b.HasOne("ComuniApi.DAL.Entidades.ConceptoEntity", "Concepto")
                        .WithMany("EdoCuentas")
                        .HasForeignKey("ConceptoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ComuniApi.DAL.Entidades.UsuarioEntity", "Usuario")
                        .WithMany("EdoCuentas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Concepto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ComuniApi.DAL.Entidades.ForoComentarioEntity", b =>
                {
                    b.HasOne("ComuniApi.DAL.Entidades.ForoEntity", "Foro")
                        .WithMany("Comentarios")
                        .HasForeignKey("ForoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ComuniApi.DAL.Entidades.UsuarioEntity", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Foro");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ComuniApi.DAL.Entidades.ForoEntity", b =>
                {
                    b.HasOne("ComuniApi.DAL.Entidades.ComunidadEntity", "Comunidad")
                        .WithMany("Foros")
                        .HasForeignKey("ComunidadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Comunidad");
                });

            modelBuilder.Entity("ComuniApi.DAL.Entidades.IncidenciaEntity", b =>
                {
                    b.HasOne("ComuniApi.DAL.Entidades.IncidenciaEstatusEntity", "Estatus")
                        .WithMany("Incidencias")
                        .HasForeignKey("EstatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ComuniApi.DAL.Entidades.UsuarioEntity", "Usuario")
                        .WithMany("Incidencias")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estatus");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ComuniApi.DAL.Entidades.ReporteEntity", b =>
                {
                    b.HasOne("ComuniApi.DAL.Entidades.ReporteEstatusEntity", "Estatus")
                        .WithMany("Reportes")
                        .HasForeignKey("EstatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ComuniApi.DAL.Entidades.UsuarioEntity", "Usuario")
                        .WithMany("Reportes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estatus");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ComuniApi.DAL.Entidades.UsuarioEntity", b =>
                {
                    b.HasOne("ComuniApi.DAL.Entidades.ComunidadEntity", "Comunidad")
                        .WithMany("Usuarios")
                        .HasForeignKey("ComunidadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ComuniApi.DAL.Entidades.RolEntity", "Rol")
                        .WithMany()
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Comunidad");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("ComuniApi.DAL.Entidades.ComunidadEntity", b =>
                {
                    b.Navigation("Foros");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("ComuniApi.DAL.Entidades.ConceptoEntity", b =>
                {
                    b.Navigation("EdoCuentas");
                });

            modelBuilder.Entity("ComuniApi.DAL.Entidades.ForoEntity", b =>
                {
                    b.Navigation("Comentarios");
                });

            modelBuilder.Entity("ComuniApi.DAL.Entidades.IncidenciaEstatusEntity", b =>
                {
                    b.Navigation("Incidencias");
                });

            modelBuilder.Entity("ComuniApi.DAL.Entidades.ReporteEstatusEntity", b =>
                {
                    b.Navigation("Reportes");
                });

            modelBuilder.Entity("ComuniApi.DAL.Entidades.UsuarioEntity", b =>
                {
                    b.Navigation("EdoCuentas");

                    b.Navigation("Incidencias");

                    b.Navigation("Reportes");
                });
#pragma warning restore 612, 618
        }
    }
}
