// <auto-generated />
using System;
using ComuniApi.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ComuniApi.Migrations
{
    [DbContext(typeof(ComuniContext))]
    [Migration("20251102190849_conceptoid_edctas")]
    partial class conceptoid_edctas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ComuniApi.DAL.Entidades.ComunidadEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("MaxUsers")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Comunidades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Correo = "",
                            Direccion = "Direccion test",
                            MaxUsers = 0,
                            Nombre = "Comunidad test"
                        });
                });

            modelBuilder.Entity("ComuniApi.DAL.Entidades.ConceptoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Conceptos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Mantenimiento"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Proyecto Extraordinario"
                        });
                });

            modelBuilder.Entity("ComuniApi.DAL.Entidades.EdoCuentaEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ConceptoId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaLimite")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConceptoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("EdoCuentas");
                });

            modelBuilder.Entity("ComuniApi.DAL.Entidades.RolEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Usuario"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Administrador"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Super Administrador"
                        });
                });

            modelBuilder.Entity("ComuniApi.DAL.Entidades.UsuarioEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ComunidadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ComunidadId");

                    b.HasIndex("RolId");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ComunidadId = 1,
                            Email = "",
                            NombreCompleto = "Administrador Principal",
                            PasswordHash = "AQAAAAIAAYagAAAAENdKRNY7Pi/okq/nwdtVGyv8nBnfQYVWghN3KwoVHf5yqBooKxBtraDW1OIoCFagbg==",
                            RolId = 3,
                            Username = "administrador"
                        });
                });

            modelBuilder.Entity("ComuniApi.DAL.Entidades.EdoCuentaEntity", b =>
                {
                    b.HasOne("ComuniApi.DAL.Entidades.ConceptoEntity", "Concepto")
                        .WithMany("EdoCuentas")
                        .HasForeignKey("ConceptoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ComuniApi.DAL.Entidades.UsuarioEntity", "Usuario")
                        .WithMany("EdoCuentas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Concepto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ComuniApi.DAL.Entidades.UsuarioEntity", b =>
                {
                    b.HasOne("ComuniApi.DAL.Entidades.ComunidadEntity", "Comunidad")
                        .WithMany("Usuarios")
                        .HasForeignKey("ComunidadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ComuniApi.DAL.Entidades.RolEntity", "Rol")
                        .WithMany()
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Comunidad");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("ComuniApi.DAL.Entidades.ComunidadEntity", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("ComuniApi.DAL.Entidades.ConceptoEntity", b =>
                {
                    b.Navigation("EdoCuentas");
                });

            modelBuilder.Entity("ComuniApi.DAL.Entidades.UsuarioEntity", b =>
                {
                    b.Navigation("EdoCuentas");
                });
#pragma warning restore 612, 618
        }
    }
}
